### PR TITLE
AllOrders renders order info

### PR DESCRIPTION
**Pull request by ooong**
- Order id, product names in order, quantity, address, status, and total

### CODE REVIEW

**Review by Asterids — CHANGES_REQUESTED** [review]
In the AllOrders component, the dispatch(fetchOrdersByUserId()) still has 3 being passed in, and should have the current user passed in. Other than that I think it looks good! I want to go through and remove console.logs but we talked about doing one big sweep at the end, so I can hold off

**Comment by ooong** [comment]
okay so I'm not seeing the userId in ownProps- isn't that info supposed to be passed down in ownProps?

**Comment by Asterids** [comment]
Hmm, perhaps we need to put it on state in mapState? I'm going to look at some other components that grab user info and maybe we can use a similar tactic

**Comment by Asterids** [comment]
Can we put a user on state via mapState, including it as { user: state.user } ?

**Comment by ooong** [comment]
closing this, opening a new pull request with the correct code and a bit of styling

**Pull request closed without merging**
