### PR TITLE
Order routes

### PR DESCRIPTION
**Pull request by Lgerald**

### CODE REVIEW

**Comment by Lgerald** [comment]
I did a few additional things besides setting up the routes: 
-when we eager load the order, we get a little too much info (ie we also get the users email and passwords), so I've added a sanitize method to the user DB model. its not being used yet, but basically what it does is send eveything BUT sensetive info. I was thinking it might be easier to use that in some cases instead of specifying which attributes to send in every route, but we can discuss that later (for now, MVP) but Its there
-also I installed lodash to implement the sanitizer, so that changed the package json a bit

**Comment by Lgerald** [comment]
just for the sake of more clarity in my routes, i also removed the isCart column from the Order model, because I figured the status should be enough to determine if a cart is a cart yeah? we can add it back later if people miss it though

**Comment by Lgerald** [comment]
the order routes are kinda janky right now, but they work! but each one requires sensetive input. I have notes in my code, but I'll go over in detail here what each route is and what it does

**Comment by Lgerald** [comment]
the GET/ route (/api/orders):
- if theres a status of some sort, will only pull up orders with said status
-otherwise it will send back all the orders and ALL their nested details (including user info and whatnot)
*this is a route that only admins should be able to use, so we need to add more security here
*also i dont think all the users info should be coming in here, so maybe we can sanitize this info later?

**Comment by Lgerald** [comment]
the GET/:orderId route (/api/orders/[somenumber]
- gets and eager loads all the info about one order
*also needs to be sanitized so user info doesnt come up

**Comment by Lgerald** [comment]
the POST/Cart (api/orders/cart)
- essentially is the creation of a cart(or an unprocessed order?)
- i misstyped in my notes, I think the only input this one will need is a userId (or maybe it doesnt?? idk)
- so what I was thinking was, upon page load in the front end, (or wherever) there can be some sort of thunk that creates this initially, so when the user comes to the site, they have a cart. it will be empty, and have the status of 'created' associated with their Id and thats it
- I havent thought too hard about how this will play our for unauthenticated users just yet, but once again, MVP

**Comment by Lgerald** [comment]
the PUT/add (/api/order/add)
- this is the one thats gonna update the quantity in our productOrder model
- we can attach this to the add to cart button
- if the user hasnt already added this item to their cart, it will create an entry in the productOrder table w/ the quantity of one
- otherwise, it will increment the quantity column by one
- idk why but i cant think of the right http statuses for these, so double check those....

**Comment by Lgerald** [comment]
the PUT/remove (/api/order/remove)
- this is essentially the same as the add, except it only takes the product order item and decrements the quantity by one
- also not sure what status would work best here

**Comment by Asterids** [comment]
From what I understand, the promise queries to the database don't necessarily automatically return a value (for instance, .update is one that I'm pretty sure you need to explicitly return), so I believe the 'return' statements should remain in the server/api/orders.js - that said, I think we hadn't finished adding 'return' statements to that route in the first place, so maybe we can go back through and address it later.

**Comment by Lgerald** [comment]
- if you NEED to change anything with this to make the front-end look/feel better when working on it, please, by all means change away! Its very basic and its incomplete but as an MVP it should serve its purposes

- I HAVE NOT set up a way to calculate the total price in the backend yet, but for our MVP i think that'll be fine for now?(as long as the price is still on the front-end as it currently is)

- Ruth: for now I'm not going to worry about the return statements because they are returning, they are properly updating the database, so as the saying goes "if it aint broke..." (MVP). for the update methods, thats why I have the {returning:true} option in them

**Review by Asterids — APPROVED** [review]

**Comment by ooong** [comment]
@Lgerald 

- When I try testing the current POST api/orders route, I get this error message: "column "isCart" of relation "orders" does not exist"- does this pull request fix that? I'm not totally sure what that error means since the Order model allows for a defaultValue of "true"
- Do we want to add the "name" field to the Order model?
- I think we should add a "total" field to the Order model. As far as I can tell, it doesn't look like we're storing the total or subtotal anywhere? It looks like we're calculating it from the product quantities and prices in the Cart component based on what's in store/cart. We know that we have to keep the total on the database eventually, so maybe you could add the "total" field and allowNull for now until we can figure out how to save it there? I kinda think we should have a "total" field in our store and then send it along with the other order information to the database

**Comment by Asterids** [comment]
@ooong Hmm, and you've pulled today, right? Have you tried re-seeding the database? Our current orders model has a field for "isCart" with a default value of "true", so it should appear in the database when a new order is posted. I will test that out again now also.

Note: I added a new issue today with the changes we decided together on making to the ProductOrders model:
- Change "ProductOrders" name to "LineItems"
- Add "PriceAtTimeOfCheckout" (or similar) field to LineItems model

**Comment by ooong** [comment]
It's weird, I see the "isCart" column in my database but I'm getting that error message which made me think that it was related to one of the new association methods. Is the route working for you? Can you show me what you're sending in Postman? I'll also try re-seeding @Asterids

**Comment by ooong** [comment]
Ack re-seeding worked!! So sorry! @Lgerald @Asterids

**Pull request merged**
